# -*- coding: utf-8 -*-
"""jewellery.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LVqUG_L4oXx_q_ErJbTmZ18rUH14vHRV
"""

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

"""# Imports"""

import numpy as np
import matplotlib.pyplot as plt
import os
import warnings
import keras
from PIL import Image
from sklearn.neighbors import NearestNeighbors

warnings.filterwarnings("ignore")

import glob

"""# Path & Images"""

path = "/kaggle/input/datasets/sapnilpatel/tanishq-jewellery-dataset/Jewellery_Data/"

image_paths = glob.glob(path + "*/*.jpg")

image_paths

"""# Cell"""

len(image_paths)

"""# MobileNetV2"""

from tensorflow.keras.applications import MobileNetV2

backbone = MobileNetV2(
    weights="imagenet",
    include_top=False,
    pooling="avg"
)

backbone.trainable = False

backbone.summary()

from tensorflow.keras.utils import load_img

load_img(image_paths[0])

from tensorflow.keras.utils import img_to_array
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

img = load_img(
    image_paths[0],
    target_size=(224, 224)
)

photos_array = img_to_array(img)

photos_array = np.expand_dims(
    photos_array,
    axis=0
)

photos_array = preprocess_input(photos_array)

photos_array.shape

embedding = backbone.predict(photos_array)

embedding.shape

"""# Function"""

def extract_embedding(image_path):
    img = load_img(
        image_path,
        target_size=(224, 224)
    )

    photos_array = img_to_array(img)
    photos_array = np.expand_dims(photos_array, axis=0)
    photos_array = preprocess_input(photos_array)

    embedding = backbone.predict(
        photos_array,
        verbose=0
    )

    return embedding[0]

"""# Embeddings"""

embeddings = []

for image_path in image_paths:
    embedding = extract_embedding(image_path)
    embeddings.append(embedding)

embeddings = np.array(embeddings)

embeddings.shape

np.savez(
    "jewelry_embeddings.npz",
    embeddings=embeddings,
    image_paths=np.array(image_paths)
)

